/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Hospital;

import model.DB4OUtil.DB4OUtil;
import model.EcoSystem.EcoSystem;
import model.Enterprise.Hospital.Doctor;
import model.Enterprise.Hospital.Hospital;
import model.Enterprise.Hospital.Patient;
import UI.Hospital.WorkArea.Admin.AdminLogin;
import UI.Hospital.WorkArea.Doctor.DoctorLogin;
import UI.Hospital.WorkArea.Patient.PatientLogin;
import UI.MainFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author smiti
 */
public class MainHospitalPage extends javax.swing.JPanel {

    /**
     * Creates new form MainHospitalPage1
     */
    MainFrame mainFrame;
    private EcoSystem ecoSystem;
    private DB4OUtil dB4OUtil;

    public MainHospitalPage(MainFrame mainFrame, DB4OUtil dB4OUtil, EcoSystem ecoSystem) {
        initComponents();
        this.mainFrame = mainFrame;
        this.dB4OUtil = dB4OUtil;
        this.ecoSystem = ecoSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dropdownRole = new javax.swing.JComboBox<>();
        lbl_username = new javax.swing.JLabel();
        lbl_Hosptitle = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lbl_pswd = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        btnSignin = new javax.swing.JButton();
        lbl_role = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dropdownRole.setEditable(true);
        dropdownRole.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dropdownRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Patient", "Nurse", "Doctor","Hospital Admin"}));
        dropdownRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownRoleActionPerformed(evt);
            }
        });
        jPanel1.add(dropdownRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 197, -1));

        lbl_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_username.setText("Username:");
        jPanel1.add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, -1));

        lbl_Hosptitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbl_Hosptitle.setText("HOSPITAL");
        jPanel1.add(lbl_Hosptitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 300, 60));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 197, -1));

        lbl_pswd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_pswd.setText("Password:");
        jPanel1.add(lbl_pswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, -1, -1));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 197, -1));

        btn_login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_login.setText("LOGIN");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 590, -1, -1));

        btnSignin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSignin.setText("SIGN UP");
        btnSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigninActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 590, -1, -1));

        lbl_role.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_role.setText("Role:");
        jPanel1.add(lbl_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 140, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255,10));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Hospital/ThoughtWire-Smart-Hospital-02.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 1220, 1110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dropdownRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownRoleActionPerformed
        // TODO add your handling code here:
        System.out.println(dropdownRole.getSelectedItem().toString());
        if (dropdownRole.getSelectedItem().toString() == "Admin") {
            btnSignin.setEnabled(false);
        } else {
            btnSignin.setEnabled(true);
        }
    }//GEN-LAST:event_dropdownRoleActionPerformed

    private void btnSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigninActionPerformed
        // TODO add your handling code here:
        if (dropdownRole.getSelectedItem().toString() == "Patient") {

            PatientSignIn signpat = new PatientSignIn(mainFrame, dB4OUtil, ecoSystem);

            //suc.setVisible(true);
            mainFrame.setContentPane(signpat);
            //             this.add(s);

            mainFrame.invalidate();
            mainFrame.validate();

        }

        if (dropdownRole.getSelectedItem().toString() == "Doctor") {

            DocSignIn doc = new DocSignIn(mainFrame, dB4OUtil, ecoSystem);
            mainFrame.setContentPane(doc);
            mainFrame.invalidate();
            mainFrame.validate();
            return;

        }
        if (dropdownRole.getSelectedItem().toString() == "Nurse") {

            NurseSignIn n = new NurseSignIn(mainFrame, dB4OUtil, ecoSystem);
            mainFrame.setContentPane(n);
            mainFrame.invalidate();
            mainFrame.validate();

        }


        if (dropdownRole.getSelectedItem().toString() == "Hospital Admin") {
            //System.out.println("Hospital");
            HospAdminSignIn s = new HospAdminSignIn(mainFrame, dB4OUtil, ecoSystem);
            mainFrame.setContentPane(s);
            mainFrame.invalidate();
            mainFrame.validate();

        }
    }//GEN-LAST:event_btnSigninActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        try{
        if (dropdownRole.getSelectedItem().toString() == "Hospital Admin") {
            Hospital ho = (Hospital) ecoSystem.loginCheck(txtUsername.getText(), txtPassword.getText());
            if(ho == null){
                JOptionPane.showMessageDialog(this, "Incorrect credential");
            }else{
                AdminLogin ap = new AdminLogin(mainFrame, dB4OUtil, ecoSystem, ho);
                mainFrame.setContentPane(ap);
                mainFrame.invalidate();
                mainFrame.validate();
                return;
            }

        }
        }catch(Exception e){
            
        }

        if (dropdownRole.getSelectedItem().toString() == "Patient") {
            System.out.println("selecteditem");
            Patient pa = (Patient) ecoSystem.loginCheck(txtUsername.getText(), txtPassword.getText());
            if (pa == null) {
                JOptionPane.showMessageDialog(this, "Incorrect credential");
            } else {
                PatientLogin pl = new PatientLogin(mainFrame, dB4OUtil, ecoSystem, pa);
                mainFrame.setContentPane(pl);
                mainFrame.invalidate();
                mainFrame.validate();
                return;
            }
        }

        if (dropdownRole.getSelectedItem().toString() == "Doctor") {
            System.out.println("selecteditem");
            Doctor dr = (Doctor) ecoSystem.loginCheck(txtUsername.getText(), txtPassword.getText());
            if (dr == null) {
                JOptionPane.showMessageDialog(this, "Incorrect credential");
            } else {
                DoctorLogin dl = new DoctorLogin(mainFrame, dB4OUtil, ecoSystem, dr);
                mainFrame.setContentPane(dl);
                mainFrame.invalidate();
                mainFrame.validate();
                return;
            }
        }
        
            if (dropdownRole.getSelectedItem().toString() == "Nurse") {

                JOptionPane.showMessageDialog(this, "Not allowed to login.");
            
        }
    }//GEN-LAST:event_btn_loginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignin;
    private javax.swing.JButton btn_login;
    private javax.swing.JComboBox<String> dropdownRole;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Hosptitle;
    private javax.swing.JLabel lbl_pswd;
    private javax.swing.JLabel lbl_role;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
