/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.DonorBank.WorkArea;

import model.DB4OUtil.DB4OUtil;
import model.EcoSystem.EcoSystem;
import model.Enterprise.DonorInventory.DonorInventory;
import UI.DonorBank.WorkArea.DonorAdmin.DonorAdminDonateOrgan;
import UI.DonorBank.WorkArea.DonorAdmin.DonorAdminDonorList;
import UI.DonorBank.WorkArea.DonorAdmin.DonorAdminTransplant;
import UI.MainFrame;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author smiti
 */
public class DonorBankAdminLogin extends javax.swing.JPanel {

    /**
     * Creates new form DonorBankAdminLogin
     */
    
    MainFrame mainScreen;
    private EcoSystem ecoSystem;
    private DB4OUtil dB4OUtil;
    DonorInventory donbank;
    
    public DonorBankAdminLogin(MainFrame mainScreen, DB4OUtil dB4OUtil, EcoSystem ecoSystem, DonorInventory donbank) {
        initComponents();
        this.mainScreen = mainScreen;
        this.dB4OUtil = dB4OUtil;
        this.ecoSystem = ecoSystem;
        this.donbank = donbank;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btn_donateOrgan = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_transplant1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        btn_donateOrgan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_donateOrgan.setText("Donate Organ");
        btn_donateOrgan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_donateOrganActionPerformed(evt);
            }
        });

        btn_logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btn_transplant1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_transplant1.setText("Transplant");
        btn_transplant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transplant1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_transplant1)
                    .addComponent(btn_logout)
                    .addComponent(btn_donateOrgan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_donateOrgan, btn_logout, btn_transplant1});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(btn_donateOrgan)
                .addGap(26, 26, 26)
                .addComponent(btn_transplant1)
                .addGap(26, 26, 26)
                .addComponent(btn_logout)
                .addGap(307, 307, 307))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_donateOrgan, btn_logout, btn_transplant1});

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.hoverBorderColor"));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/DonorBank/WorkArea/donor2.v4.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_donateOrganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_donateOrganActionPerformed
        // TODO add your handling code here:
        DonorAdminDonateOrgan dado = new DonorAdminDonateOrgan(mainScreen, dB4OUtil, ecoSystem, donbank);
        jSplitPane1.setRightComponent(dado);
    }//GEN-LAST:event_btn_donateOrganActionPerformed

    private void btn_transplant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transplant1ActionPerformed
        // TODO add your handling code here:
        DonorAdminTransplant dat = new DonorAdminTransplant(mainScreen, dB4OUtil, ecoSystem, donbank);
        jSplitPane1.setRightComponent(dat);
    }//GEN-LAST:event_btn_transplant1ActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        MainFrame suc = new MainFrame();
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        suc.setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_donateOrgan;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_transplant1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
