/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Admin;

import model.DB4OUtil.DB4OUtil;
import model.EcoSystem.EcoSystem;
//import model.Firebase.FirebaseHelper;
import UI.MainFrame;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Shardul
 */
public class AdministrationSplitPage extends javax.swing.JPanel {

    /**
     * Creates new form AdministrationSplitPage
     */
    MainFrame mainFrame;
//    FirebaseHelper firebaseHelper;
    private EcoSystem ecoSystem;
    private DB4OUtil dB4OUtil;

    public AdministrationSplitPage(MainFrame mainFrame, DB4OUtil dB4OUtil, EcoSystem ecoSystem) {
        initComponents();
        this.mainFrame = mainFrame;
        this.dB4OUtil = dB4OUtil;
        this.ecoSystem = ecoSystem;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        dbMgmt = new javax.swing.JButton();
        hospMgmt = new javax.swing.JButton();
        transplantMgmt = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        logMgmt = new javax.swing.JButton();
        dispGraph = new javax.swing.JButton();
        techMgmt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jSplitPane1.setDividerSize(10);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        dbMgmt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dbMgmt.setText("Manage Donor Inventory");
        dbMgmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbMgmtActionPerformed(evt);
            }
        });

        hospMgmt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        hospMgmt.setText("Manage Hospital");
        hospMgmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospMgmtActionPerformed(evt);
            }
        });

        transplantMgmt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        transplantMgmt.setText("Manage Transplants");
        transplantMgmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transplantMgmtActionPerformed(evt);
            }
        });

        logoutBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        logMgmt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        logMgmt.setText("Manage Logistics");
        logMgmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logMgmtActionPerformed(evt);
            }
        });

        dispGraph.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dispGraph.setText("Graphs");
        dispGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispGraphActionPerformed(evt);
            }
        });

        techMgmt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        techMgmt.setText("Manage Tech");
        techMgmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                techMgmtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dbMgmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transplantMgmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logMgmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dispGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(techMgmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hospMgmt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(hospMgmt)
                .addGap(30, 30, 30)
                .addComponent(dbMgmt)
                .addGap(29, 29, 29)
                .addComponent(transplantMgmt)
                .addGap(32, 32, 32)
                .addComponent(techMgmt)
                .addGap(31, 31, 31)
                .addComponent(logMgmt)
                .addGap(27, 27, 27)
                .addComponent(dispGraph)
                .addGap(28, 28, 28)
                .addComponent(logoutBtn)
                .addContainerGap(847, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Admin/Medical-Wallpapers-HD-Free-download.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(92, 92, 92))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(296, 296, 296))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hospMgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospMgmtActionPerformed
        // TODO add your handling code here:
        ManageAdminHosp ap = new ManageAdminHosp(mainFrame, dB4OUtil, ecoSystem);
        jSplitPane1.setRightComponent(ap);
    }//GEN-LAST:event_hospMgmtActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        MainFrame suc = new MainFrame();
        ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        suc.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void dbMgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbMgmtActionPerformed
        // TODO add your handling code here:
        ManageDonorInventory mdb = new ManageDonorInventory(mainFrame, dB4OUtil, ecoSystem);
        jSplitPane1.setRightComponent(mdb);
    }//GEN-LAST:event_dbMgmtActionPerformed

    private void logMgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logMgmtActionPerformed
        // TODO add your handling code here:

        ManageLogistics mdb = new ManageLogistics(mainFrame, dB4OUtil, ecoSystem);
        jSplitPane1.setRightComponent(mdb);
    }//GEN-LAST:event_logMgmtActionPerformed

    private void transplantMgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transplantMgmtActionPerformed
        // TODO add your handling code here:
        ManageTransplant mt = new ManageTransplant(mainFrame, dB4OUtil, ecoSystem);
        jSplitPane1.setRightComponent(mt);
    }//GEN-LAST:event_transplantMgmtActionPerformed

    private void dispGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispGraphActionPerformed
        // TODO add your handling code here:
//        ManageTransplant mt = new ManageTransplant(mainFrame, dB4OUtil, ecoSystem);
        Graphs mt = new Graphs(mainFrame, dB4OUtil, ecoSystem);
        jSplitPane1.setRightComponent(mt);
    }//GEN-LAST:event_dispGraphActionPerformed

    private void techMgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_techMgmtActionPerformed
        // TODO add your handling code here:
        ManageTech mtech = new ManageTech(mainFrame, dB4OUtil, ecoSystem);
        jSplitPane1.setRightComponent(mtech);
    }//GEN-LAST:event_techMgmtActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dbMgmt;
    private javax.swing.JButton dispGraph;
    private javax.swing.JButton hospMgmt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logMgmt;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton techMgmt;
    private javax.swing.JButton transplantMgmt;
    // End of variables declaration//GEN-END:variables
}
