/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.DonorBank;

import model.DB4OUtil.DB4OUtil;
import model.EcoSystem.EcoSystem;
import model.Enterprise.DonorInventory.DonorDetails;
import model.Enterprise.DonorInventory.DonorInventory;
//import model.Firebase.FirebaseHelper;
import UI.DonorBank.WorkArea.DonorBankAdminLogin;
import UI.DonorBank.WorkArea.DonorLogin;
import UI.MainFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author smiti
 */
public class MainDonorBankPage extends javax.swing.JPanel {

    /**
     * Creates new form MainDonorBankPage
     */
    MainFrame mainScreen;
    private DB4OUtil dB4OUtil;
    private EcoSystem ecoSystem;

    public MainDonorBankPage(MainFrame mainScreen, DB4OUtil dB4OUtil, EcoSystem ecoSystem) {
        initComponents();
        this.mainScreen = mainScreen;
        this.dB4OUtil = dB4OUtil;
        this.ecoSystem = ecoSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_role = new javax.swing.JLabel();
        cmb_Role = new javax.swing.JComboBox<>();
        lbl_username = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lbl_pswd = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        btnSignin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("HelpButton.focusedBorderColor"));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DONOR BANK");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        lbl_role.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_role.setText("Role:");
        add(lbl_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, -1, -1));

        cmb_Role.setEditable(true);
        cmb_Role.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_Role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Donor","Donor Admin"}));
        cmb_Role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_RoleActionPerformed(evt);
            }
        });
        add(cmb_Role, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 197, -1));

        lbl_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_username.setText("Username:");
        add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, -1, -1));
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 197, -1));

        lbl_pswd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_pswd.setText("Password:");
        add(lbl_pswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, -1, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 197, -1));

        btn_login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 86, -1));

        btnSignin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSignin.setText("Sign Up");
        btnSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigninActionPerformed(evt);
            }
        });
        add(btnSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/DonorBank/donor2.v4.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 1300, 750));
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_RoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_RoleActionPerformed
        // TODO add your handling code here:
        System.out.println(cmb_Role.getSelectedItem().toString());
        if (cmb_Role.getSelectedItem().toString() == "Admin") {
            btnSignin.setEnabled(false);
        } else {
            btnSignin.setEnabled(true);
        }
    }//GEN-LAST:event_cmb_RoleActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        
        if (cmb_Role.getSelectedItem().toString() == "Donor Admin") {
            DonorInventory donbank = (DonorInventory) ecoSystem.loginCheck(txtUsername.getText(), txtPassword.getText());
            if(donbank == null){
                JOptionPane.showMessageDialog(this, "Incorrect credential");
            }else{
                DonorBankAdminLogin ap = new DonorBankAdminLogin(mainScreen, dB4OUtil, ecoSystem, donbank);
                mainScreen.setContentPane(ap);
                mainScreen.invalidate();
                mainScreen.validate();
                return;
            }
        }
        
        if (cmb_Role.getSelectedItem().toString() == "Donor") {
            DonorDetails don = (DonorDetails) ecoSystem.loginCheck(txtUsername.getText(), txtPassword.getText());
            if(don == null){
                JOptionPane.showMessageDialog(this, "Incorrect credential");
            }else{
                DonorLogin ap = new DonorLogin(mainScreen, dB4OUtil, ecoSystem, don);
                mainScreen.setContentPane(ap);
                mainScreen.invalidate();
                mainScreen.validate();
                return;
            }
        }

        //        if (cmb_Role.getSelectedItem().toString() == "Doctor") {
        //            Customer c = system.loginCustomer(txtUsername.getText(), txtPassword.getText());
        //            if (c == null) {
        //                JOptionPane.showMessageDialog(this, "Incorrect credential");
        //            } else {
        //                CustomerMainPage custmp = new CustomerMainPage(system, dB4OUtil, c);
        //                this.setContentPane(custmp);
        //                this.invalidate();
        //                this.validate();
        //                return;
        //            }
        //
        //        }
        //        if (cmb_Role.getSelectedItem().toString() == "Nurse") {
        //            Restaurant r = system.loginResaturant(txtUsername.getText(), txtPassword.getText());
        //
        //            if (r == null) {
        //                JOptionPane.showMessageDialog(this, "Incorrect credential");
        //            } else {
        //                RestaurantMainPage restmp = new RestaurantMainPage(system, dB4OUtil, r);
        //                this.setContentPane(restmp);
        //                this.invalidate();
        //                this.validate();
        //                return;
        //            }
        //
        //        }
        //
        //        if (cmb_Role.getSelectedItem().toString() == "Patient") {
        //            DeliveryMan r = system.loginDeliveryMan(txtUsername.getText(), txtPassword.getText());
        //
        //            if (r == null) {
        //                JOptionPane.showMessageDialog(this, "Incorrect credential");
        //            } else {
        //                DeliverManMainPage delimp = new DeliverManMainPage(system, dB4OUtil, r);
        //                this.setContentPane(delimp);
        //                this.invalidate();
        //                this.validate();
        //                return;
        //            }
        //
        //        }
        //
        //        if (cmb_Role.getSelectedItem().toString() == "Hospital Admin") {
        //            if (txtUsername.getText().matches("a") && txtPassword.getText().matches("a")) {
        //                AdminPage adminpg = new AdminPage(system, dB4OUtil);
        //                this.setContentPane(adminpg);
        //                this.invalidate();
        //                this.validate();
        //                return;
        //            } else {
        //                JOptionPane.showMessageDialog(this, "Incorrect credential");
        //            }
        //        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btnSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigninActionPerformed
        // TODO add your handling code here:

       
        if (cmb_Role.getSelectedItem().toString() == "Donor") {

            SignUpDonor signdon = new SignUpDonor(mainScreen, dB4OUtil, ecoSystem);
//
//            //suc.setVisible(true);
            mainScreen.setContentPane(signdon);
////            //             this.add(s);
////
            mainScreen.invalidate();
            mainScreen.validate();

        }

        if (cmb_Role.getSelectedItem().toString() == "Donor Admin") {
           // System.out.println("Hospital");
            SignUpDonorAdmin s = new SignUpDonorAdmin(mainScreen, dB4OUtil, ecoSystem);

            //suc.setVisible(true);
            mainScreen.setContentPane(s);
            //             this.add(s);

            mainScreen.invalidate();
            mainScreen.validate();

        }
    }//GEN-LAST:event_btnSigninActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignin;
    private javax.swing.JButton btn_login;
    private javax.swing.JComboBox<String> cmb_Role;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_pswd;
    private javax.swing.JLabel lbl_role;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
